### PR TITLE
Convert THT resistor script

### PR DESCRIPTION
**Pull request by Franck78**
to run python3
to adopt recent change (same script as Converter DCDC)

cq_parameters:

moved the color info in each variant
changed color of SIP resistor to Red
added two sizes for the power vishay CPCC serie: CPC10 CPCC1A
Can't tell if previous CPCC10 was an error (pitch=7.37 ??) it is no more
in the PDF

Remove lot of eol spaces character

Suggestion: use green body for power round resistor, Sfernice like.

adding vishay CPCC  CPC10 CPCC1A 3dimages was the primary goal

### CODE REVIEW

**Comment by easyw** [comment]
Hi @Franck78 
have you tested the changes on win, Linux & OSX?
I noticed that on line 11 of the launching script you have changed '$1' with 'all' but the script should accept a parameter... moreover you changed 'freecad' with 'FreeCAD', but on Linux (which is case sensitive) the script will not work with your modification.  
https://github.com/easyw/kicad-3d-models-in-freecad/blob/32cb130e7d4817e6601573e6864cd9f80bf741c8/cadquery/FCAD_script_generator/Resistor_THT/create_model.sh#L11

ATM I'm not able to check the scripts on OSX, so you should confirm that the changes are working on all OSs.

**Comment by Franck78** [comment]
Hello,

$1 or all : I'm not sure what 'launcher.sh' is the correct. I took example from DCDC converters, which itself was copied from 'molex' which have neither $1 or all. This will be useful if someday a higher level calls all the scripts (like make).
Perso, I put the name of the model I'm testing directly

* I will put $1
* I don't do Window
* I don't do Mac

If you do a diff with main_generator.py from DCDC_converters, you will find little difference except the make_body make_pins function of course.
If you tell me which main_generator.py is the most uptodate, I will base this one on it and others.


"you changed 'freecad' with 'FreeCAD',"
yes, that the official name of it.
FreeCAD

**Comment by easyw** [comment]
> "you changed 'freecad' with 'FreeCAD',"
> yes, that the official name of it.

@Franck78  in which repo are you? on Debian it should be all lowercase ... could it be gentoo?

> * I don't do Window
> * I don't do Mac

that's a really issue... it should require some other developer testing... I'm going to see if we can just go on merging and later wait for users's issues...

**Comment by Franck78** [comment]
OpenSuse leap 15.2

I think Leap is correct. Look here how FreeCAD themselves call it

https://github.com/FreeCAD/FreeCAD/blob/master/src/fc.sh

https://github.com/FreeCAD/FreeCAD/blob/master/src/App/FreeCADInit.py

I didn't find the "main.c" producing the executable.

About windows, I think if there is a problem, it will be more in the external environment to the the script that in the script. The code is basic (I can read it ;) ). No super advanced python tricks. 

Specific to this script, you can see that introducing the 'Array' resistor makes a lot of 'if' and 'else'. Other than the name 'Resistor' there is nothing in common between drawing the two.
That makes me think the params_tupple thing in cq_paramters should contain information like colors, dest_dir_prefix, range, shape in it instead of inside the script.

I also like the 'molex' organisation with lots of cq_paramsfiles doing one model.

**Comment by easyw** [comment]
on ubuntu we have 'freecad' and not 'FreeCAD' ... anyway most users would be able to fix it...

**Comment by Franck78** [comment]
now I have to try to 'up' pointhi to add my footprint generators, fix the power resistor list, because 3dimages ok, but without footprints,..... 

Do you have a particular script to fix ?

**Pull request merged**
