### PR TITLE
Phoenix contact, add geometry check, correct file names and update license

### PR DESCRIPTION
**Pull request by poeschlr**

### CODE REVIEW

**Comment by easyw** [comment]
Thx

**Comment by poeschlr** [comment]
You are faster than my internet can upload the 3d files to the packages 3d lib.

**Comment by easyw** [comment]
:smile: mobile power ;)

**Comment by poeschlr** [comment]
I noticed that the step files are now a lot smaller. Seems there is a better step exporter in freecad now. (compared to the fc 0.15 exporter that i originally used to export the phoenix models.)

**Comment by easyw** [comment]
> I noticed that the step files are now a lot smaller. Seems there is a better step exporter in freecad now. 

FreeCAD 0.17 is much better indeed for STEP importing/exporting, manipulating and it is blazer faster :smile:
Moreover it is in code freezing, the new stable release is near!

**Pull request merged**
