### PR TITLE
scripts of SF_IA, SF_IH, SF_ITX and SF_ITQ series of XP_POWER DCDC converters

### PR DESCRIPTION
**Pull request by ferdymercury**
cannot generate the 3D model myself, please check.

### CODE REVIEW

**Comment by Misca1234** [comment]
You do not have to add Converter_DCDC_XP_POWER-IAXXXXS_SIP_THT
It is already there, it was included in the fix for the rim

**Comment by Misca1234** [comment]
Change rim line from
rim = (6.09, 0.5, 0.5),          # If a rim should be created at the bottom
To
rim = (0.5, 0.5, 0.5),          # If a rim should be created at the bottom

I can generate Converter_DCDC_XP_POWER-IAXXXXS_SIP_THT

bild

**Comment by ferdymercury** [comment]
> You do not have to add Converter_DCDC_XP_POWER-IAXXXXS_SIP_THT
> It is already there, it was included in the fix for the rim

I saw it, but I think it had a typo, because the variable was named "'Converter_DCDC_XP_POWER-IAXXXXS_SIP_THT': Params, but then below the model was named        modelName = 'Converter_DCDC_XP_POWER-IA48XXXXS_DIP_THT', which is inconsistent.

**Comment by ferdymercury** [comment]
> Converter_DCDC_XP_POWER-IAXXXXS_SIP_THT

The rim should go all the way along x, not just four corners. I am not sure if it should be then 6.09 or 6.09/2

**Comment by Misca1234** [comment]
the rim works like this, it will cut off a slice of the belly of the body, if you make one direction, the 6.09 wide enough to cut the whole belly you actually slices off the body height, you will notice this on the foot print+3D model, the body belly seems to be "to high" much higher than A1 above the PCB

You should add to the main_generator.py two if cases, when the corresponding cut direction parameter is 0.0, it wont cut the belly in that direction.

**Comment by ferdymercury** [comment]
Fixed.

**Comment by easyw** [comment]
@ferdymercury 
is this PR ready to be merged?

**Comment by ferdymercury** [comment]
Yes it is, I compared it with all footprints through kicad stepup and they match together

**Comment by easyw** [comment]
thx :smile:

**Pull request merged**
