### PR TITLE
Added model Maxim_WLP-12_4x3_2.0x1.56mm_Pitch0.5 in the BGA directory

### PR DESCRIPTION
**Pull request by Misca1234**
Added the maxim specific model WLP-12
http://pdfserv.maximintegrated.com/package_dwgs/21-0009.PDF
Model W121B2+1

### CODE REVIEW

**Comment by easyw** [comment]
Thx for your contribution 
:smile:

**Comment by Misca1234** [comment]
Np, it is very easy to add them
My next next one is this, txb0104
http://www.ti.com/lit/ds/symlink/txb0104.pdf
It comes in 
UQFN (12)
SOIC (14)
BGA MICROSTAR JUNIOR (12)
TSSOP (14)
VQFN (14)
DSBGA (12)

I guess that SOIC and TSSOP exist already and 
UQFN, VQFN, if they dont exist, should go into QFN_packages
DSBGA, BGA MICROSTAR JUNIOR, if they dont exist, should go into BGA_packages ?

**Comment by Misca1234** [comment]
Btw, who are these 3D models going into the 3D-model directory in KiCad, is this done by you each week , or is it up to me to fork and push them myself ?

**Comment by easyw** [comment]
> DSBGA, BGA MICROSTAR JUNIOR, if they dont exist, should go into BGA_packages ?
I would say so...

> Btw, how are these 3D models going into the 3D-model directory in KiCad, is this done by an librarian each week , or is it up to me to fork and push them myself ?

it is normally used to make a double PR for packages3D and kicad-library
see here
https://github.com/KiCad/packages3D/issues/24

**Comment by Misca1234** [comment]
ok, great, i will push the 3d models as wlel

**Pull request merged**
