### PR TITLE
Update other molex scripts

### PR DESCRIPTION
**Pull request by poeschlr**
**Do not merge yet** (I will notify you as soon as i have done everything that i want to do with this.)

### CODE REVIEW

**Comment by easyw** [comment]
this time I'm going to wait 😉

**Comment by poeschlr** [comment]
Do "parallel" edge selectors work for you with newer cadquerry modules (1.x)
Example: .edges("|Z")
For me this always returns an empty stack.

**Comment by easyw** [comment]
> Do "parallel" edge selectors work for you with newer cadquerry modules (1.x)
Example: .edges("|Z")

this issue seems removed by release 0.17 12703

**Comment by easyw** [comment]
sorry @poeschlr 
it seems I was wrong... I still get this issue on "|Z" ... it is related to CQ

**Comment by poeschlr** [comment]
Ok. Thanks for testing. (I also just tested it in my ubuntu vm. Same result)
Well for now i export the models without these fillets and chamfers. Maybe it will be fixed or somebody finds time to implement a workaround via the box selection.

**Comment by easyw** [comment]
@poeschlr 
as a workaround you could check using CQ 0.52, which works fine form me

**Comment by poeschlr** [comment]
Yay it works.
Well at least the part about the edge selector. Now i need to repair the slimstack models because BOP reports a lot of errors.

**Comment by easyw** [comment]
in win64 i.e. 'KK_6410_01x16_2_54mm.step' is fine... does it report errors for you?
PS I checked the same in DSM and I found no issue either

**Comment by easyw** [comment]
Which OCC release are you with?

**Comment by poeschlr** [comment]
The problem was the slimstack 54722. There a sharp edge was fused with a face.

In fedora i use:
OCC version: 6.9.1.oce-0.18

**Comment by easyw** [comment]
Good oh then!
I'm glad the BOP checker is useful :smile:
PS OCC 7 are giving an other bost in STEP quality!

**Comment by poeschlr** [comment]
Not even the 5 day old ubuntu daily does include OCC 7.
If you have OCC 7 running could you test how much smaller the step file is for the slimstack model.

To generate it start `FreeCAD main_generator.py series=54722 model_filter=80`
If there is a notable reduction i might look into getting OCC 7 to run on one of my systems. (Current file size for the step model: 5.2MB)

**Comment by easyw** [comment]
Which OCC release are you with?

**Comment by easyw** [comment]
I will have a try... But OCC 7 has enhanced multi-threading and boolean operations ... it shouldn't be any size touching

**Comment by poeschlr** [comment]
Ok i just looked again. Ubuntu does use OCC 7.1
I already started the generator. (I don't think i will get a lot of a speed boost because the ubuntu is in a VM.)

**Comment by easyw** [comment]
https://forum.freecadweb.org/viewtopic.php?f=4&t=21246 
Ubuntu is in OCC 7.1

**Comment by easyw** [comment]
Oops we crossed the posts

**Comment by poeschlr** [comment]
On ubuntu i get `No module named Gui.Command` but i discovered that this import does not seem to be needed any more.

And the file size does increase. By a lot! Now it is 22MB instead of 5.2MB

**Comment by easyw** [comment]
file size doens't depend on OCC release... 
you may try to copy your cfg files from the FC you were using and the new one and re-generate the series

**Comment by poeschlr** [comment]
@easyw i think these are all the finished generators re done. (The remaining molex generator has a lot of fixme and todo's in it. There are also no models for that series in the official repo.)

**Comment by easyw** [comment]
Thx

**Pull request merged**
