### PR TITLE
add Stocko MKS 3D generator script

### PR DESCRIPTION
**Pull request by balcer**
Hi, this is a script for generating Stocko MKS 3D models.

### CODE REVIEW

**Comment by easyw** [comment]
Hi @balcer 
I've noticed from your linked pdf, that you should use 'gold' as material for pins.
I also noticed that the exported STEP file is not unioned as a single object.

It should be done by your generating script, similarly as in
https://github.com/easyw/kicad-3d-models-in-freecad/blob/master/cadquery/FCAD_script_generator/Connector_PinHeader/main_generator.py
` FuseObjs_wColors(FreeCAD, FreeCADGui,
doc.Name, objs[0].Name, objs[1].Name)`

**Comment by balcer** [comment]
Hi, @easyw. here is a photo of the connector. As far as I know, this is not a gold plated pins. I use these connectors every day and I have never seen gold plated. Please write to me on which page did they mention about gold plated pins. I only found information on page 32.  They write about 3 types of surface finish. And gold is the last one. I think that tin-plated are the most popular. 



Ok, I will add STEP union.

Thanks for the review.

**Comment by balcer** [comment]
Oh, and please check if the license is added correctly to both types of files.

**Comment by easyw** [comment]
Hi @balcer 
I saw the golden pins from the site you linked:
https://www.hz-profishop.com/product_info.php?info=p622_mks-1857-6-0-707-s38-grau-.html
image
Anyway, feel free to chose gold or silver as you prefer.
Step files are fine now.
Thanks for your contribution.
:smile:

**Comment by balcer** [comment]
Hi @easyw Thank for merge. Is 3D PR is ok also?

**Comment by easyw** [comment]
From my side is fine... you should ask to kicad 3d repo, because I'm not a k librarian.

**Pull request merged**
