### PR TITLE
Molex 5569 series (Mini-Fit Jr Angled with pegs)

### PR DESCRIPTION
**Pull request by timtashpulatov**
First attempt with cadquery and Python. A few details still missing (like small ribs on the side, and splits in pegs, and contact cavities all square), but still could be useful.

### CODE REVIEW

**Comment by easyw** [comment]
Hi @timtashpulatov 
thx for your script... the result is very nice! 😸 
molex-new
from what I see the script can run only manually loading it in FC-CQ WB and running it from there...
This repository has been refactored to let the user launch the script from a batch command like that:
start "" "C:\Program Files\FreeCAD 0.15\bin\freecad" main_generator.py
so it would possible to:
1) rename the script to main_generator.py
2) adapt the script to be executed by command line
3) adding a bat and a sh file to launch the script from command line
4) adding all option to create all family products
5) adding the export to STEP and WRL models, with materials
6) adding a README.md file

thx a lot for this nice model to be added to the lib!
Maurice

**Comment by Shackmeister** [comment]
Nice work! Are you planning on adding the details and all the export settings or is it provided "as it"? :)

**Comment by timtashpulatov** [comment]
Thanks Maurice, I'll try to make the script compliant with those requirements. Also will add missing details.

**Comment by timtashpulatov** [comment]
It would possibly help to have some sort of template(s) or a quick guide on how to add new components to the library. Or I am just missing some docs here :)

**Comment by easyw** [comment]
Hi @timtashpulatov 
thanks for going into it
the simplest repo to have a look as a template is 
https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator/capacitors_SMD
there you will found all the needed files.
here you can find a related discussion on how we started the refactoring
https://github.com/easyw/kicad-3d-models-in-freecad/issues/28

**Comment by easyw** [comment]
I looked at the main_generator.py and I would add the following code to the script to let it run from a command line batch

> import sys, os
> from sys import argv
> sys.path.append("../_tools")
> 
> scriptdir=os.path.dirname(os.path.realpath(__file__))
> sys.path.append(scriptdir)
>

**Comment by timtashpulatov** [comment]
Thanks @easyw, in fact I have already been copying the Capacitors_SMD scripts :-) will add more stuff from there.

**Comment by Shackmeister** [comment]
Im currently in the process of changing all the output path to a accordingly named .3dshapes folder so it's possible to generate all the scripts and have a ready to go library. I would be very glad if you can add /.. /Connectors_Molex.3dshapes or whatever fits :) can you post a Screenshot with the latest details? :)

**Comment by Shackmeister** [comment]
body = body.cut(cq.Workplane("XY")
                        .box(body_width, cavity_width, cavity_width)
                        .edges("|X").edges("<Z").chamfer(cavity_width/4)
                        .translate((bx-1, offset, dia/2 + pitch))
                        )
works quite nice for the non square pins but I cant really find the pattern for when they are square and when they are not :s

**Comment by timtashpulatov** [comment]
Nice one @Shackmeister :) The pattern is rather simple, it is NSSNNSS... sequence, starting from 1st pin. S is  square, N is non-square. Pin 1 is always N.
Bottom cavity is always of the opposite shape, i.e. for 10-pin connector it will be like this:
SSNNS <--- pin 1, top row
NNSSN <--- pin 6, bottom row

Here's a shot of connector with side rib. The datasheet from Molex does not give all necessary constraints, so have to fiddle with the Ruler tool in FreeCAD over original STEP model to figure out certain obscure dimensions.

image

**Comment by Shackmeister** [comment]
nice :) shouldnt be too bad to add the pattern in the code :)
does Molex have other families which are similar but different in size or similar? :)

**Comment by timtashpulatov** [comment]
Will add pattern, just need some time to get myself more familiar with FreeCAD and Python. There is a number of variations for this particular Molex family: single- or double-row, right angled or vertical, and with pegs or PCB mounting flanges. All share the same pitch (4.2mm) and row distance (5mm).

image

**Comment by Shackmeister** [comment]
Awesome :) seems like you are getting the hang of it :) 
This was also my first encounter with freecad and python :) (pretty sure I still don't know how to manually model something in freecad) 
But please don't hesitate to ask if I can be helpful with something :)

**Comment by easyw** [comment]
Hi @timtashpulatov 
if you are ok I can merge this PR, you can then add the export STEP & VRML later on...
Maurice

**Comment by timtashpulatov** [comment]
@easyw would be great, I did not make it to add export and standalone run touches yet.

**Comment by easyw** [comment]
I'm going to add also a readme and basic launching scripts

**Comment by easyw** [comment]
thx a lot for your contribution 😸

**Comment by timtashpulatov** [comment]
@easyw Maurice thanks a lot for your help :)

**Pull request merged**
