### PR TITLE
Tantal add geometry check plus new names

### PR DESCRIPTION
**Pull request by poeschlr**
**To not merge yet**

This pull request will add geometry check to tantal caps.
I will also update the naming convention stuff and make it easier to change the naming convention.

I also cleaned up my other generators by moving the geometry check stuff into cq_tools
And i moved the output dir to _3dmodels

### CODE REVIEW

**Comment by easyw** [comment]
@poeschlr 
Rene, do you think it would be nice to add also the following checks to the tools?
1) if FC 0.16 is used and is < 0.16-6712, stop the execution
(previous releases have an extra container added to STEP files and didn't show the extra container if the step file is reloaded in the same release, then checkUnion will not fail, but the model would have an extra container)
2) if FC is < 0.17 and check_Model=True, stop the execution  
(BOP check doesn't work fine in previous releases of FC)

**Comment by poeschlr** [comment]
I am not really convinced it is a good idea to simply stop the execution. (For committing to the official lib the checks need to be made. But people can also use these scripts to generate personal models for their own use.)
I think the log file approach is better. We can then request the contributor to add the log file to the PR. (That's why i used markdown for the log file. It will then be rendered rather nicely in github. Sadly there is no way to use colored text otherwise i would have colored pass green, fail red and skipped yellow.)

Adding a check for defect freecad versions to the union check should be possible.

**Comment by easyw** [comment]
I tend to avoid having models with errors in geometry also for my personal use and I consider this a very needed condition for a good/safe mechanical library ... That's why I started with a stopper for the model generator. I fear the normal user would not even notice the log file ... but a stop condition would raise with every user...

**Comment by poeschlr** [comment]
Stopping on first error is a no go for large generator scripts like for example the phoenix generator. There it takes quite a long time till everything is generated. Getting a report for all models that fail makes it much easier to debug the problem then failing on first problem would. 
As soon as i have a list of models that fail i can then use the filter options to generate only affected models and regenerate them until none of them have geometry errors any more.

The initial run can even happen over night or while i am at lunch, ....

I can include a fail on error but there must be an option to turn this off. And a illegal instruction is definitely not the right way to go about this.

Also it is a lot easier to inspect the models using the graphical tools in freecad afterwards. (Import step models that failed the test and use the check geometry button from the part workbench. This shows you where the error is.) But for this the step file needs to exist.

**Comment by easyw** [comment]
> Stopping on first error is a no go for large generator scripts like for example the phoenix generator.
 There it takes quite a long time till everything is generated. Getting a report for all models that fail makes it much easier to debug the problem then failing on first problem would.

For a family generator normally the geometry error would be similar to all wrong models, so the process to found a solution for one will probably solve all.

> I can include a fail on error but there must be an option to turn this off. And a illegal instruction is definitely not the right way to go about this.

It is just a stopper in developing the script.. I see no issue in just stopping the builder...

> Also it is a lot easier to inspect the models using the graphical tools in freecad afterwards. (Import step models that failed the test and use the check geometry button from the part workbench. This shows you where the error is.) But for this the step file needs to exist.

But you forgot that if you stop the execution, you stop it when you have already generated and imported the model... so the STEP file exists for manual inspection...
Stopping on first error will avoid to lose time in generating all models that may be afflicted by the same issue...
That is why I approached the BOP checking with a stopper and not a logger...
May be we can add a var to switch between stop or log...

**Comment by poeschlr** [comment]
@easyw i now added such a error handling. The geometry check function now throws two possible exceptions.
One exception for invalid Freecad versions.
One exception for invalid geometry (not unioned or BOB check failed.)
The version exception always kills my generators if check models is active. 

The geometry exception only kills the generator if a stop_at_first_error parameter is True (default behavior). In my generators with more powerful command line options (phoenix, jst, molex), this behavior can be changed with the command line switch "error_tolerant".

**Comment by easyw** [comment]
@poeschlr 
please let me know if it is ready to be merged

**Comment by poeschlr** [comment]
@easyw now it should be ready to merge.

**Comment by easyw** [comment]
thx 😄

**Pull request merged**
