### PR TITLE
Added scripts for generating transformers

### PR DESCRIPTION
**Pull request by Misca1234**
Push of three transfomers

Initiated be the push 
https://github.com/KiCad/kicad-packages3D/pull/548

Data sheet
http://www.sanyourelay.ca/public/products/pdf/SRD.pdf

The models are scripted

3D model push
https://github.com/KiCad/kicad-packages3D/pull/564

3D model script push
https://github.com/easyw/kicad-3d-models-in-freecad/pull/286

bild

bild

bild

### CODE REVIEW

**Comment by easyw** [comment]
@Misca1234 
is that correct to call them transformers... aren't they relays?

**Comment by easyw** [comment]
thx

**Comment by Misca1234** [comment]
Jee, too fast copy and paste, fixing it

**Comment by Misca1234** [comment]
Ahhh, yo umean in the push title, that is a type, but in the scripts they are called relays

**Pull request merged**
