### PR TITLE
Added script to generate 2.54mm pitch dual-row box headers

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Hey @easyw 

I have created a simple script for generating generic box-headers

box_headers

Cheers

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
These align pin-1 @ (0,0) and output with the filename in "correct" KiCAD format

**Comment by easyw** [comment]
thanks for your contribution :+1:

**Comment by SchrodingersGat** [comment]
Feel free to add all these models to your 3D repo, too!

**Comment by easyw** [comment]
Rene is going to add the new VRML exporter routines to some of these scripts ... so everything will be optimized for nice 3D rendering 
keep in touch :+1:

**Comment by easyw** [comment]
Hi again Oliver,
if you want @poeschlr has done the wrl export routines for export wrl with materials
at the moment the code is done only for qfn models, but can be easily ported to all :+1: 
you may consider it also for pin-headers and box-headers
Maurice

**Pull request merged**
