### PR TITLE
Added Phoenix terminal block serie MKDS, 5.08mm Horizontal

### PR DESCRIPTION
**Pull request by Misca1234**
This is a scripted version of Phoenix terminal block MKDS serie 5.08 mm

https://www.phoenixcontact.com/online/portal/gb/?uri=pxc-oc-itemdetail:pid=1715802&library=gben&pcck=P-11-01-05&tab=1&selectedCategory=ALL

On request by  easyw in push
https://github.com/KiCad/kicad-packages3D/pull/567

Pins 2 to 16 is generated with script

3D model push
https://github.com/KiCad/kicad-packages3D/pull/571

3D model script push
https://github.com/easyw/kicad-3d-models-in-freecad/pull/288

bild

bild

bild

### CODE REVIEW

**Comment by easyw** [comment]
Hi @Misca1234 
very good job as always!
Thx a lot
Maurice

**Comment by tolot27** [comment]
I wonder why Altechs AK300 appears in this commit. Is this intentional?

**Comment by tolot27** [comment]
How is pin 1 defined? In the datasheet I could not find any numbering or default orientation.

I'm asking because I wan't to push some scripts to generate additional Phoenix Contact terminal blocks.

**Comment by Misca1234** [comment]
> I wonder why Altechs AK300 appears in this commit. Is this intentional?

The push was an adaption of the AK300 script, when I added the MKDS script it seems that I forgot to remove the AK300 parameter, you can remove AK300 if you add new phoneix connectors



> How is pin 1 defined? In the datasheet I could not find any numbering or default orientation.
> I'm asking because I wan't to push some scripts to generate additional Phoenix Contact terminal blocks.

It don't, it depends on how you solder it on the PCB in the end, so if you want to turn it correct, according how you want to mount it, you need to rotate the 3D model when you make the PCB/3D view

**Comment by easyw** [comment]
@Misca1234 
normally it is numbered from left to right, seeing the block from front... (I added numbering to the mkds image).
mkds

**Pull request merged**
