### PR TITLE
added CP_Tantal_generator

### PR DESCRIPTION
**Pull request by Shackmeister**
for some reason CP_Radial_Tantal_D9.0mm_Px.xxmm crashes in FC0.16 but works fine in FC0.17.. its driving me mad! can you please have a look at it @easyw?

### CODE REVIEW

**Comment by easyw** [comment]
no problem on windows 

> OS: Windows 10
> Word size of OS: 64-bit
> Word size of FreeCAD: 64-bit
> Version: 0.16.6710 (Git)
> Build type: Release
> Branch: releases/FreeCAD-0-16
> Hash: f8eca0f9311f07c125dd6742a607724c1fa0b77c
> Python version: 2.7.8
> Qt version: 4.8.7
> Coin version: 4.0.0a
> OCC version: 6.8.0.oce-0.17
> 

cp-tantalum

PS an other very nice job Man! 😺

**Comment by Shackmeister** [comment]
Hi can you please try to generate all? Im not sure why it gave the error :/

**Comment by easyw** [comment]
this model 
CP_Radial_Tantal_D6.0mm_P5.00mm
and some others have problems...
It seems that some operations behave differently on OCC 7.1 compared to OCC 6.80-oce

OCC 7.1
fc017-model

OCC 6.80-oce
wrong-model

You may change the way of building the models or wait few days for FC0.17 to be patched ...

**Comment by Shackmeister** [comment]
Hmm I don't really know other ways, I could remove the small revolution part and just add the two legs together (this was the way Jan did it) 

Is there a way to figure out what should be changed to support the other OCC it seems like it doesnt cut correctly in 6.80

**Comment by Shackmeister** [comment]
Oh perhaps my cadquery for 0.16 is outdated

**Comment by easyw** [comment]
I would wait few days... Jean Marie is already working on the FC017 placement issue... It could be ready after the weekend :smile:

**Comment by easyw** [comment]
OCC 7.1 has so many improvements compared to OCE 6.8 that I wouldn't care too much and just would consider these models valid only for FC0.17 and OCC7.1

**Comment by Shackmeister** [comment]
Is FC0.17 running OC7. 1 or how are the relation?

**Comment by Shackmeister** [comment]
Still annoying xD Oh Well :p but now all the THT capacitors are ported to cadquery :) the nice thing I generate all the parameters from the footprint scripts :) makes everything much faster! Next will be chip inductors and then THT resistors and Leds

**Comment by easyw** [comment]
Great work!!! Looking forward to see Inductors Resistors and LEDs!!! Best MCAD library in the world! ;)
PS FC0.17 is bundled with OCC7.1

**Comment by Shackmeister** [comment]
should SMD LEDS be generated in all the colors or simply one? most LED's look the same anyway when its not on

**Comment by easyw** [comment]
I would generate all the colors models as per led lighted ... but you are in the decision 😄

**Comment by Shackmeister** [comment]
But then we would need a footprint for each :p all the decisions!

**Pull request merged**
