### PR TITLE
Assorted DIP parts

### PR DESCRIPTION
**Pull request by terjeio**
Turned pin sockets and THT/SMD switches - for review

Newbie at this so need to learn about the level of detail required for models++

I have made my scripts class based and are using inheritance as this feels more natural to me, but as I am a newbie to pyton programming too so there may be room for further improvements.

Example part:

 
bilde

### CODE REVIEW

**Comment by Shackmeister** [comment]
Kameloso!

**Comment by easyw** [comment]
HI @terjeio 
the models look great!
I tried to build the default model 'DIP-8_W7.62mm' but I get an exception and the building stops.
Which version of FC have you built the models with? OS? CQ?
thanks
Maurice

**Comment by terjeio** [comment]
@easyw 

Thanks.

I run FC 0.16 6712 and CadQuery 1.0.0 on Win 7/64bit
Did you load and run the script from within FC or start FC from a batch file?

There is a minor bug that results in a crash _after_ all models are built from a batch file, near the end of main_generator.py:

` for i in range(0, len(variants) - 1):
            for variant in variants:`

should be:

`for i in range(0, len(parts)):
            for variant in variants:`

Did you get a stack trace for the exception? Any trace output from the process?

Of course it is possible to change the models, you guys decide what is acceptable or not.

**Comment by easyw** [comment]
Hi 

> Did you load and run the script from within FC or start FC from a batch file?

I run the script from a batch file...
If I run it without a parameter it runs finely, but if I run the batch with a parameter, it will raise the exception.

> create_model.bat DIP-8_W7.62mm

I also tried to pass 'all' and in that case it is working...

> 'create_model.bat all'

**Comment by terjeio** [comment]
@easyw  ok, I will implement the changes

I have also improved command line parsing, since cq_parameters.py contains generic model parametes I had to generate a new dictionary with the dynamically made model names, these can now listed with the _list_ argument. From a updated README.adoc:

to run the script just move to the scripts dir and do:
freecad ./main_generator.py all|allsmd|list|\<variant\>|\<filter\>
all - generate all models
allsmd - generate all SMD models
list - list all model names
\<variant\> - a variant from the generic names in cq_parameters.py
\<filter\> - a reqular expression matching model names in the models list

examples in win:
c:\freecad\bin\freecad main_generator.py DIP-10
c:\freecad\bin\freecad main_generator.py *Piano*
c:\freecad\bin\freecad main_generator.py allsmd
in linux: 
freecad ./main_generator.py DIP-10
freecad ./main_generator.py *Piano*
freecad ./main_generator.py all
or simply run the 'create_model' script/batch

it is also possible to run the script with no arguments, default models placed on the matching footprint (requires kicad StepUp module) will then be generated

---

As there is a whole host of different coding styles in the existing scripts it is not easy for a newbie to pick the best way of coding, ...and I will only  add to the confusion if my contribution is accepted.

Terje

**Comment by Shackmeister** [comment]
@Misca1234 did you guys make the same models?

**Comment by Misca1234** [comment]
Well, apparently we made our effort without knowing each other
I only started with SMD models but I think terjeio made tht variant as well,
I dont mind he overwrite mine

**Comment by easyw** [comment]
> As there is a whole host of different coding styles in the existing scripts it is not easy for a newbie to pick the best way of coding, ...and I will only add to the confusion if my contribution is accepted.

I think that most of us when we started were just a first approach to programming in python... if the code run smoothly, no confusion at all 😸

**Comment by easyw** [comment]
> Well, apparently we made our effort without knowing each other
I only started with SMD models but I think terjeio made tht variant as well,
I dont mind he overwrite mine

By my side, I think I'm going to merge both of the 3D model generators.. they can cohabit each others and they both make nice models 😄 
I will let the librarians to choose which of them will be merged to the k 3d lib

**Comment by terjeio** [comment]
@easyw Hold back on merging these for a while, I have to check the footprints again for non-standard 3d-parameters. 

The footprints for socket strips I am working on (520, not 2000) are obviously script generated and many have non-standard parameters. I need to make a PR for 3d-parameter changes, a script bug and a spelling mistake for those first to get more familiar with the whole process, A good thing is that the footprint script has documentation references to the parts :-) 

Should the step and wrl files have a pointer in the header to the script used to make them? Also, there is a bug somewhere (minor) that adds lots of blank comment lines to the file headers, maybe in my code since I do not see that in the pin header models.

**Comment by easyw** [comment]
> Should the step and wrl files have a pointer in the header to the script used to make them? 

that could be a nice adding 😄

**Comment by terjeio** [comment]
Final changes? I have made the main_generator.py code more generic for simpler reuse,  added a pointer to the source in the generated files and fixed a "bug" in the license generator code++

**Comment by easyw** [comment]
@terjeio 
if you are fine I'm going to merge those!
Thx for your contribution and welcome to MCAD squad!
😸

**Comment by terjeio** [comment]
@easyw 

Thanks, I believe the models are ok now so go ahead.

It pleasure to be able contribute. I started with electronics design again a few years ago after a long stint as a programmer and KiCad is a IMO fantastic tool considering it is open source. My previous PCB designs was done with Rotring pens and transfer decals, the world has come a long way since then...

As a test of the generic nature of part of my code I have just made a script for the IDC headers, I will soon make a PR for that. I will have to make a PR for the footprints also as they do not contain model references, and must check to see if they are generated by script. Better cross-referencing in the files would be nice.

The socket strips are another story, the models are (nearly) ready to go but the footprints need updating. Adding another 1GB+ to the KiCad download is a bit premature too?

**Comment by easyw** [comment]
thanks for your contribution! 😄

**Pull request merged**
