### PR TITLE
Added 3D models of audio jacks

### PR DESCRIPTION
**Pull request by Misca1234**
Added a number of 3D models fo the audio jacks

3D model push
https://github.com/KiCad/kicad-packages3D/pull/495

3D model script push
https://github.com/easyw/kicad-3d-models-in-freecad/pull/254

bild

bild

bild

bild

bild

### CODE REVIEW

**Comment by easyw** [comment]
Wow, very nice!!! :hoorray:

**Comment by Misca1234** [comment]
Thx, is not one of them yours ?

**Comment by easyw** [comment]
no, I just need a model some time ago and I had to search at online 3d repos... better having them in kicad official repos :smile:

**Comment by Franck78** [comment]
RED jack in the corner have pins inverted (Y only)

Changes the Y sign and it's OK  (eg swap 3.25 & -3.25)

diff --git a/cadquery/FCAD_script_generator/Connector_Audio/cq_audio_jack_qingpu.py b/cadquery/FCAD_script_generator/Connector_Audio/cq_audio_jack_qingpu.py
index 0fbcfd1..13e962f 100644
--- a/cadquery/FCAD_script_generator/Connector_Audio/cq_audio_jack_qingpu.py
+++ b/cadquery/FCAD_script_generator/Connector_Audio/cq_audio_jack_qingpu.py
@@ -551,7 +551,7 @@ class cq_audio_jack_qingpu():
 
             A1 = 0.01,                                      # Body-board separation
 
-            pin = [['smd', -3.175, 3.25, 1.2, 2.5, 0.2], ['smd', -0.175, 3.25, 1.2, 2.5, 0.2], ['smd', 3.825, 3.25, 1.2, 2.5, 0.2], ['smd', 4.925, -3.25, 1.2, 2.5, 0.2]],
+            pin = [['smd', -3.175, -3.25, 1.2, 2.5, 0.2], ['smd', -0.175, -3.25, 1.2, 2.5, 0.2], ['smd', 3.825, -3.25, 1.2, 2.5, 0.2], ['smd', 4.925, 3.25, 1.2, 2.5, 0.2]],
             npthpin = [['pin', -4.775, 0.0, 1.5, 2.0], ['pin', 2.225, 0.0, 1.5, 2.0]],
             body_top_color_key  = 'metal aluminum',         # Top color
             body_color_key      = 'red body',               # Body color

**Pull request merged**
