### PR TITLE
Started making code PEP8 compliant, fixed macro bug, added a large number of additional packages.

### PR DESCRIPTION
**Pull request by metacollin**
Hi, I cleaned up the files that other users would probably spend the most time in to make them more readable and easier to work with.  All of them are 100% compliant with the PEP8 Python code style guide, and have passed all lint checks.  

I've also added a significant number of additional packages, as well as made it possible to specify certain pins to exclude on gullwing packages arbitrarily.  This allows easy creation of the SOT/TSOT style packages as well as certain high voltage variants that have a missing pin as a safety gap.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@metacollin I like the idea of skipping pins! Very cool.

**Comment by easyw** [comment]
thank you for contribution :) :+1:

**Comment by metacollin** [comment]
Thanks! And if you don't like the style changes or anything, just change whatever and I'll pull it into my fork.  I just want to help improve an awesome tool.  It's been incredibly useful to me, so it's the least I can do.

**Comment by easyw** [comment]
@metacollin if you have some time my target would be to gradually align all the module generators to the new VRML exporter which gives the VRML a much **smaller size** and also material properties...
the code has been added, at the moment, only to qfn models
thanks again for your code :)

**Pull request merged**
