### PR TITLE
Added TFBGA-121_10x10mm_Layout11x11_P0.8mm

### PR DESCRIPTION
**Pull request by Misca1234**
Push of TFBGA-121_10x10mm_Layout11x11_P0.8mm
http://ww1.microchip.com/downloads/en/PackagingSpec/00000049BQ.pdf#p495

Both foot print and 3D model is script based

Foot print push
https://github.com/KiCad/kicad-footprints/pull/1013

Foot print script push
https://github.com/pointhi/kicad-footprint-generator/pull/199

3D model push
https://github.com/KiCad/kicad-packages3D/pull/418

3D model script push
https://github.com/easyw/kicad-3d-models-in-freecad/pull/205

bild

bild

### CODE REVIEW

**Comment by easyw** [comment]
Hi,
you may consider to exclude internal pins from generation, to reduce STEP file size
`        excluded_pins = ("internals"), #pins to exclude -> None or "internals"`

**Comment by Misca1234** [comment]
Fixed

**Comment by Misca1234** [comment]
Fixed

**Comment by Misca1234** [comment]
bild

**Comment by easyw** [comment]
Thx

**Pull request merged**
