### PR TITLE
DPAK / D2PAK / D3PAK / ATPAK: add script

### PR DESCRIPTION
**Pull request by hackscribble**
Added CadQuery script and supporting modules for DPAK, D2PAK, D3PAK and ATPAK packages.
Updated README.
Removed superseded script (old PR was https://github.com/easyw/kicad-3d-models-in-freecad/pull/49)

image

## Main PR
https://github.com/KiCad/kicad-library/pull/1204

## Related PRs
https://github.com/KiCad/packages3D/pull/43

### CODE REVIEW

**Comment by easyw** [comment]
thx a lot! very nice stuff!!!
The library is growing day by day! 😸

**Comment by easyw** [comment]
PS I added 
`sys.path.append("./")`
to execute the scripts from command line in win

**Comment by hackscribble** [comment]
I keep forgetting that :smile: I will tidy that up and push another PR.

**Comment by easyw** [comment]
ok thx 😺

**Comment by easyw** [comment]
BTW I like the yaml structure for data 😸 
that is opening the road to i.e. inductors with asimmetric pads an other complex models!

**Pull request merged**
