### PR TITLE
Add script for TO-220-7Lead_TabPin8

### PR DESCRIPTION
**Pull request by hackscribble**
Created `TO_SOT_Packages_SMD_custom` folder and `README.md` file.
Added CadQuery script and supporting module.

## Main PR
https://github.com/KiCad/kicad-library/pull/1193

## Related PRs
https://github.com/KiCad/packages3D/pull/40

### CODE REVIEW

**Comment by easyw** [comment]
Hi @hackscribble 
the script is very nice and **could open a scenario to a new family to create TO asymmetric models!** 😸 
it would be possible to add to the code the option to create a FC file and export the model to _3Dmodels folder adding colors? 
To test the script I also had to add 

> import sys, os
> sys.path.append("./")

before

> from ribbon import Ribbon

Thx for your great additions!
Maurice

**Comment by hackscribble** [comment]
Thanks @easyw I will add the path - it works OK without it on my system, but I will add and then check it still works - just in case there is a compatibility issue.

About extending the script, I would add the FC create and export functionality (as in `main_generator.py`) **if** I decided to extend it to other devices as you suggest.  And I am interested in looking at that but have a couple of questions:

- There are already models for about 40 devices in `TO_SOT_Packages_SMD.3dshapes`.  Do you think there are still big gaps in coverage of TO asymmetric?
- Do you know of a document / website that has the footprint details in one place?  Searching through individual datasheets doesn't sound like fun :cry:

**Comment by easyw** [comment]
@hackscribble I'm adding @Shackmeister to this conversation...
He did the work to extend sot packages to many asymmetric models and he was suggesting me to improve the generation for other models... He can suggest better the models to be included...

Regarding having a single doc to collect all footprint details is a difficult subject...
here
http://www.vishay.com/mosfets/tapereel-package-list/
there is a table summarizing many TO devices with a column for Outline Drawing with dimensions that could help

Please consider this is only a suggestion... I would merge it also without these changes... I just wanted to point out that this is a good opportunity to add a new way to create models with CQ scripts using your 'Ribbon' approach (very nice though :smile:)
Maurice

**Comment by Shackmeister** [comment]
hey @hackscribble there are still quite a few TO packages needed mainly anyone which has flat pins/pad instead of gullwings. I was considering adding and option to set each pin induvidualy to either a GW or a flat pins... also I was thinking about adding an option in exclude_pins to set a value to 2.5 to only have half of the pin. would be used for TO-252 etc.

**Comment by hackscribble** [comment]
Thanks @Shackmeister and @easyw I will look into this.

In the meantime @easyw could you please merge this PR.  Extending the script will take me a while.

**Comment by easyw** [comment]
Merged ... 
thx a lot...
😺

**Pull request merged**
