### PR TITLE
Added the SO-6L model in the SOIC directory

### PR DESCRIPTION
**Pull request by Misca1234**
Added the SO-6L model to the SOIC directory

bild

### CODE REVIEW

**Comment by easyw** [comment]
Thx for your contribution!
Welcome to kicad MCAD squad! :smile:

**Comment by Misca1234** [comment]
Np, nice to be onboard

**Comment by Misca1234** [comment]
Btw, I have this chip MAX5813 
http://pdfserv.maximintegrated.com/package_dwgs/21-0009.PDF
Thye call it WPL-12 but i guess it is a derivate of BGA, should I add it as a WLP-12 or a BGA-12 ?
It is a slight difference with distances and ball sizes but not much

**Comment by easyw** [comment]
I would conserve its name as from the manufacturer, but for kicad naming standards it is better to ask to @SchrodingersGat @jkriege2  @poeschlr 
😸

**Comment by Shackmeister** [comment]
I believe it should keep the original name but go in the housing_WLCSP. Pretty repo (if you feel like all the other footprints in there are lacking 3d models :)) remember there is a BGA generator in this repo

**Comment by jkriege2** [comment]
Hmmm ... Why SCP and not BGA?
For the naming I would keep the name WPL-12. If it's specific to Maxim (which I suspect), I would use the form `Maxim_WLP-12` ... otherwise you should use a full BGA-specification, e.g.: `BGA-12_4x3_2.0x1.55mm_Pitch0.5mm`

Best,
JAN

**Comment by SchrodingersGat** [comment]
The differentiation between many of the `BGA` and `CSP` packages is subtle. This could easily fit within either repo.

The instruction by @jkriege2 above is correct, regarding manufacturer specific part numbering.

**Pull request merged**
