### PR TITLE
Better capacitor generators

### PR DESCRIPTION
**Pull request by poeschlr**
Adding geometry checker to capacitor generator.
Change name generation to use a format string found in the config files. (Allows easy changing for different naming conventions.)
Combine different capacitor generators similar to how i did it with my connector generators. (reduce code duplication.)

**This is still a work in progress.**

### CODE REVIEW

**Comment by poeschlr** [comment]
The polarized capacitors report errors. I could reduce them by making the colored band protrude slightly from the remaining body, but some models still report geometry errors. I will check them in catia later on.

**Comment by poeschlr** [comment]
Checked the files in catia (after removing the one troublesome dot) and they seem to be ok.

**Comment by easyw** [comment]
@poeschlr 
unfortunately we have very little tools to check geometry in FC. 
What I noticed is that:
* FC0.16 is almost useless to check geometry because of OCC 6
* FC0.17 has a better BOP checker with OCC 7
* FC0.17 can give false positives, but in general if there are no warnings, it means the model is just fine
* FC0.17 can give less warnings, but a first level of check with a Shape checker.

[I'm attaching the BOP (already used in 3d models generation) and Shape checkers for a fast comparison]
[check-BOP-Shape.zip](https://github.com/easyw/kicad-3d-models-in-freecad/files/1693210/check-BOP-Shape.zip)

**Comment by poeschlr** [comment]
I am a bit short on time currently. (I never made the PR for the axial polarized cap models over on the package3d repo. I also want to add other tht cap generators to the new main script. I hope i will find some time later this week.)

**Comment by poeschlr** [comment]
@easyw this is now ready for review.

The models for the disc and rect caps where already ok in the repo so i did not create a pull request for them. I "only" checked that the new script generates the same models.

**Comment by easyw** [comment]
they look fine for me... (I just tested the Axial models)
pcb
Thx for your very useful work and continued effort! 😺 

BTW does it work for you the 'Global Spread and Place' all footprints in pcbnew (I'm on dev release)?
In mine it dosn't work and it is a real pitty for spreading out all footprints when testing 3D models...

**Comment by poeschlr** [comment]
I never tested that feature. For me kicad spreads out footprints anyways if i use the update pcb from schematic tool. (I am on a 2 year old nightly on the computer where i design my projects. I use kicad 4.0.6 and todays nightly only to test library contributions. There i normally do not create a schematic and import the netlist into pcb_new.) You could make a bug report about that.

---

Also i do not create a schematic for such a testproject but add the footprints from within pcb_new. 
I use the add footprint button in pcb_new and the lib browser. (The browser remembers what i selected last so i just click the next footprint in line when i want to add all footprints of a series.)

Do you have a script that does this automatically? (It is a lot of work otherwise.)

**Comment by easyw** [comment]
> Do you have a script that does this automatically? (It is a lot of work otherwise.)

yes of course... scripts are a time saving
I develop a base fow win
and then @Shackmeister developed something for linux
I'm attaching the window's version here
[create-pcb-from-modules.zip](https://github.com/easyw/kicad-3d-models-in-freecad/files/1939774/create-pcb-from-modules.zip)
just copy the script in the directory where all the fp are located and launch the script... it will create a kicad_pcb but with all the fp at the same position.
Then the Global Spread Footprints will do the rest of the job
https://forum.kicad.info/t/auto-arrange-components/3228/3
docs.kicad-pcb.org/4.0.7/en/pcbnew.html#_loading_new_footprints

**Comment by easyw** [comment]
@poeschlr 
the Global Spread Footprints is now back in town! 😃

**Pull request merged**
