### PR TITLE
Add molex 6410 series

### PR DESCRIPTION
**Pull request by hackscribble**
Hi @easyw This is the script used for PR: https://github.com/KiCad/packages3D/pull/34

When I was designing the script, I looked at the ones already in your repo.  I found it easier to understand and work with the `phoenix_contact` script than the existing `molex` script.  That's why this PR is in a different folder `molex_6410` to avoid clashes with the molex files.

If you prefer, I can try to add my new code to the existing `molex` scripts, though I think this will need  changes to the top-level `export_conn_molex.py` as well as the `conn_molex_nnnnn.py` files.

Please let me know what you think.

### CODE REVIEW

**Comment by easyw** [comment]
@hackscribble 
thx for your PR...
> That's why this PR is in a different folder molex_6410 to avoid clashes with the molex files.

it is fine to have those in a different folder imo...
> If you prefer, I can try to add my new code to the existing molex scripts

if you could, what is really needed is to align your new scripts to the new way of organize the folders...
Particularly it would be nice to have the models generated in the '_3Dmodels' folder with a 'Molex_6410' sub-folder, with the common tool file 'cq_helpers.py' in '_tools' folder and possibly using the 'add_license.py' file instead of the one in use now.

please keep me informed 😄 
Thx again
Maurizio

**Comment by hackscribble** [comment]
Thanks @easyw   I will make those changes and update the PR.   

To confirm, the folders `_3Dmodels` and `_tools` are the ones in the `kicad-3d-models-in-freecad/cadquery/FCAD_script_generator/` folder?

**Comment by easyw** [comment]
Exactly 
Thx

**Comment by hackscribble** [comment]
Can I clarify that this is how the license file should work?

- Import `add_license` from `_tools` into my export script
- In my script, define details which supersede the default values in `add_license`
```
# example:
STR_licAuthor = "Ray Benitez"
STR_licEmail = "hackscribble@outlook.com"
STR_licOrgSys = ""
STR_licPreProc = ""

```


- Call `addLicenseToStep()`

```
    L.addLicenseToStep(out_dir+'/', FileName+".step", LIST_license,\
        STR_licAuthor, STR_licEmail, STR_licOrgSys, STR_licPreProc)
```

**Comment by easyw** [comment]
yes ... this is the way in which it should work

**Comment by hackscribble** [comment]
PR updated:

- Added `_tools` to path for importing `add_license` and `cq_helper` 
- Removed equivalent files from my script directory
- Changed output directory to `3dmodels/Molex_6140`

**Comment by easyw** [comment]
thx a lot!

**Pull request merged**
