### PR TITLE
[WIP] Python 3 Compatibility

### PR DESCRIPTION
**Pull request by Qbort**
Fix Python 3 (FreeCad 0.18) compatibility.

Other fixes / cleanup carried out:
- Removed ribbon.py duplicate in cadquery/FCAD_script_generator/4UCON_17809/cq_models/ribbon.py
- Defined reload_lib() in cq_cad_tools.py for cleaner code
- More functionality added to check_requirements() for cleaner code:
   *Created open_CQ_Example() - this is required to be called before close_CQ_Example(), otherwise an exception is raised
   *Added tests open_CQ_Example() and close_CQ_Example() into check_requirements().
   *Removed references of close_CQ_Example() in the files from modules 4UCON_17809, BGA_packages and QFN_packages, since this is covered by check_requirements().

Current status:
- [x] 4UCON_17809
- [x] Altech
- [x] Battery
- [x] BGA_packages
- [x] Box_Headers
- [x] Buzzer_Beeper
- [x] Capacitor_THT
- [x] Connector_Audio
- [x] Connector_Coaxial
- [ ] Connector_Dsub
- [ ] Connector_FFC-FPC
- [ ] Connector_PinHeader
- [ ] Connector_USB
- [ ] Conn_PinSocket
- [ ] Conn_Stocko
- [ ] Converter_ACDC
- [ ] Converter_DCDC
- [ ] CP_Radial_SMD
- [ ] CP_Radial_THT
- [ ] CP_Tantalum_SMD
- [ ] CP_Tantalum_THT
- [ ] Crystal
- [ ] C_Chip_SMD
- [ ] C_Trimmer
- [ ] diodes_SMx_SMD
- [ ] DIP_packages
- [ ] DIP_parts
- [ ] Directfet_SMD
- [ ] exportVRML
- [ ] Filter
- [ ] Flat_Pin_packages
- [ ] Fuse
- [ ] GW_QFP_SOIC_SSOP_TSSOP_SOT
- [ ] Inductors_SMD
- [ ] jst
- [ ] LED_SMD
- [ ] L_Chip_SMD
- [ ] molex
- [ ] Molex_5569
- [ ] mounting_wuerth
- [ ] Package_SIP
- [ ] phoenix_contact
- [ ] Potentiometer_THT
- [x] QFN_packages  
- [ ] Relay_THT
- [ ] resistors_array_SMD
- [ ] Resistor_SMD
- [ ] Resistor_THT
- [ ] RF_Antenna_Chip_SMD
- [ ] Standoff_FF_MF
- [ ] Switch_SMD
- [ ] TerminalBlock_Phoenix
- [ ] TO_SOT_Packages_SMD_custom
- [ ] Transformer_THT
- [ ] Valves
- [ ] Varistor
- [ ] WIP

### CODE REVIEW

**Comment by Qbort** [comment]
First commit:
- 4UCON_17809  - Tested FC 0.17 & FC 0.18
- BGA_packages - Tested FC 0.17 & FC 0.18
- QFN_packages - Tested FC 0.17 & FC 0.18. Fixes issue #373  Note: In FreeCad 0.17 the "Report View" shows the warning "File format not supported: DFN-6-1EP_1.2x1.2mm_P0.4mm_EP0.3x0.94mm ", but it still generates the 3D model

**Comment by Qbort** [comment]
@easyw Before I go too far with these changes, would you be able to check the ones I've done so far in case you want me to change the approach?

In particular regarding reload_lib. I have defined this function just once in  cq_cad_tools.py so that I don't need to keep re-creating the function.

Thanks.

**Comment by Qbort** [comment]
Altech & Battery done & tested

**Comment by Qbort** [comment]
Box_Headers done & tested

**Comment by Qbort** [comment]
Buzzer_Beeper generator module marked as done for purpose of this pull request (all python3 fixes are done). However there is another issue that needs resolving. See: #375

**Comment by easyw** [comment]
Thx

**Comment by Qbort** [comment]
@easyw  I hadn't finished yet... i had only done 10 out of 57 modules. It was marked as [WIP] for that reason...

Anyway I'll keep working on updates offline and submit a merge request when I'm finished to avoid too many merge requests.

**Pull request merged**
